= Aansluitingenregister

:toc:
:toclevels: 3
:parent: Aansluitingenregister

[WARNING,caption="Let op"]
--
Deze website is in opbouw. Pagina's kunnen onvolledige of onjuiste informatie bevatten.
--

NBility-functie: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8[C.6.2.1. Aansluitingen/allocatiepunten beheren]

_Het aansluitingenregister bevat alle elektriciteits- en gasaansluitingen in Nederland._

Bron: https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&z=2025-01-01&g=2025-01-01[Informatiecode elektriciteit en gas]

Het aansluitingenregister wordt gezamenlijk beheerd door de netbeheerders en bevat zowel fysieke als administratieve gegevens over aansluitingen. Het register is essentieel voor de werking van de energiemarkt omdat het de basis vormt voor processen zoals leverancierswisselingen, verhuizingen en facturatie.

De verplichting tot het bijhouden van het aansluitingenregister is vastgelegd in de Informatiecode elektriciteit en gas, vastgesteld door de Autoriteit Consument en Markt (ACM).


image::model.drawio.svg[title="Diagram"]

.Legenda
[%collapsible]
====
Komt nog!
====


.LinkML
[%collapsible]
====

[source,yaml]
....
name: aansluitingenregister
annotations:
  nbility_function:
    tag: nbility_function
    value: C.6.2.1. Aansluitingen/allocatiepunten beheren
description: Het aansluitingenregister bevat alle elektriciteits- en gasaansluitingen
  in Nederland.
title: Aansluitingenregister
comments:
- Het aansluitingenregister wordt gezamenlijk beheerd door de netbeheerders en bevat
  zowel fysieke als administratieve gegevens over aansluitingen. Het register is essentieel
  voor de werking van de energiemarkt omdat het de basis vormt voor processen zoals
  leverancierswisselingen, verhuizingen en facturatie.
- De verplichting tot het bijhouden van het aansluitingenregister is vastgelegd in
  de Informatiecode elektriciteit en gas, vastgesteld door de Autoriteit Consument
  en Markt (ACM).
source: https://wetten.overheid.nl/jci1.3:c:BWBR0037934&amp;hoofdstuk=2&amp;paragraaf=2.1&amp;z=2025-01-01&amp;g=2025-01-01
id: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
version: 1.1.2
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  aansluitingenregister:
    prefix_prefix: aansluitingenregister
    prefix_reference: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister/
  nbnl:
    prefix_prefix: nbnl
    prefix_reference: https://begrippen.netbeheernederland.nl/energiesysteembeheer/nl/page/
  nbility:
    prefix_prefix: nbility
    prefix_reference: https://nbility-model.github.io/NBility-business-capabilities-Archi/
default_prefix: aansluitingenregister
default_range: Tekst
types:
  EAN-18:
    name: EAN-18
    description: Europees artikelnummer van achttien cijfers
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    typeof: Tekst
    base: str
    pattern: ^[0-9]{18}$
  Datum:
    name: Datum
    description: kalenderdatum, zonder tijdsaanduiding
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: date
  Geheel getal:
    name: Geheel getal
    description: getal zonder decimalen
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: int
  Getal:
    name: Getal
    description: voorstelling van een hoeveelheid
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: float
  Tekst:
    name: Tekst
    description: aanduiding bedoeld voor mensen, zonder vaste structuur of betekenis
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: str
  Tijdsduur:
    name: Tijdsduur
    description: lengte van een tijdsinterval, bijvoorbeeld een uur of een dag
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: duration
  Tijdstip:
    name: Tijdstip
    description: exacte aanduiding van datum en tijd, inclusief eventueel tijdzone-informatie
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: datetime
  Waar of onwaar:
    name: Waar of onwaar
    description: binaire aanduiding die aangeeft of een propositie of kenmerk van
      toepassing is (waar) of niet van toepassing is (onwaar)
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: bool
  URI:
    name: URI
    description: uniforme aanduiding van een externe of interne bron
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    base: uri
enums:
  Energiedrager:
    name: Energiedrager
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    permissible_values:
      elektriciteit:
        text: elektriciteit
      gas:
        text: gas
      waterstof:
        text: waterstof
  Groot of klein:
    name: Groot of klein
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    permissible_values:
      groot:
        text: groot
      klein:
        text: klein
  Marktsegment:
    name: Marktsegment
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    permissible_values:
      grootverbruikaansluiting:
        text: grootverbruikaansluiting
        exact_mappings:
        - nbnl:grootverbruikaansluiting
      kleinverbruikaansluiting:
        text: kleinverbruikaansluiting
        exact_mappings:
        - nbnl:kleinverbruikaansluiting
slots:
  EAN-code:
    name: EAN-code
    description: unieke cijfercombinatie volgens de Europese Artikelnummer-standaard
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    range: EAN-18
    required: true
  energiedrager:
    name: energiedrager
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    exact_mappings:
    - nbnl:energiedrager
    range: Energiedrager
classes:
  Aangeslotene:
    name: Aangeslotene
    annotations:
      nbility_object:
        tag: nbility_object
        value: Klant
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
      tijdlijn_effectuering:
        tag: tijdlijn_effectuering
        value: true
      levensduur:
        tag: levensduur
        value: true
      levensduur_begin:
        tag: levensduur_begin
        value: moment van geboorte
      levensduur_einde:
        tag: levensduur_einde
        value: moment van overlijden
    comments:
    - Aangeslotenen worden niet uniek geïdentificeerd. Daarom gaat het hier om een
      gegevensgroep bij een aansluiting, niet om een zelfstandige entiteit.
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    see_also:
    - https://wetten.overheid.nl/jci1.3:c:BWBR0037934&amp;hoofdstuk=2&amp;paragraaf=2.9&amp;sub-paragraaf=2.9.2&amp;artikel=2.9.2.1&amp;z=2022-12-20&amp;g=2022-12-20
    - https://wetten.overheid.nl/jci1.3:c:BWBR0037934&amp;hoofdstuk=3&amp;paragraaf=3.3&amp;sub-paragraaf=3.3.1&amp;artikel=3.3.1.1&amp;z=2023-06-28&amp;g=2023-06-28
    exact_mappings:
    - nbnl:aangeslotene
    attributes:
      geboortedatum:
        name: geboortedatum
        description: datum van de bevalling waarbij de aangeslotene is geboren
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
      naam:
        name: naam
        description: naam van een organisatie of de achternaam (zonder tussenvoegsel)
          van een natuurlijk persoon
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        required: true
      tussenvoegsel:
        name: tussenvoegsel
        description: verzameling van een of meer voorzetsels en/of lidwoorden die
          aan de achternaam van een aangeslotene vooraf gaat en daarmee gezamenlijk
          de volledige achternaam vormt
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
      voorletters:
        name: voorletters
        description: verzameling letters die wordt gevormd door de eerste letter van
          alle in volgorde voorkomende voornamen van een aangeslotene
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
      KVK-nummer:
        name: KVK-nummer
        description: identificatie van de maatschappelijke activiteit van de aangeslotene
          in het Handelsregister
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
      beschikker over:
        name: beschikker over
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: 0..1
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Aansluiting
        required: true
        multivalued: false
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - beschikker over
  Aansluiting:
    name: Aansluiting
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    comments:
    - Een koppeling met een gesloten distributiesysteem wordt in dit register beschouwd
      als aansluiting als de beheerder geen gebruik maakt van het elektronische berichtenverkeer
      ten behoeve van het faciliteren van derdentoegang ([artikel 2.4, vierde lid
      van de Netcode elektriciteit](https://wetten.overheid.nl/jci1.3:c:BWBR0037940&amp;hoofdstuk=2&amp;paragraaf=2.1&amp;artikel=2.4&amp;z=2023-04-01&amp;g=2023-04-01)).
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    exact_mappings:
    - nbnl:aansluiting
    narrow_mappings:
    - nbility:aansluiting
    slots:
    - EAN-code
    - energiedrager
    attributes:
      gecontracteerde transportcapaciteit:
        name: gecontracteerde transportcapaciteit
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        exact_mappings:
        - nbnl:gecontracteerde-transportcapaciteit
      grootte:
        name: grootte
        description: aanduiding van het formaat van de aansluiting op basis van de
          gewenste aansluitcapaciteiten van de overdrachtspunten
        comments:
        - &#39;Validatie: als de gewenste aansluitcapaciteit van een van de overdrachtspunten
          &#39;&#39;groot&#39;&#39; is of een geheel getal dan &#39;&#39;groot&#39;&#39; anders &#39;&#39;klein&#39;&#39;.&#39;
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Groot of klein
        required: true
        equals_expression: &#39;&#39;
      marktsegment:
        name: marktsegment
        description: aanduiding van de categorie waartoe de aansluiting behoort, te
          weten kleinverbruikaansluiting of grootverbruikaansluiting
        comments:
        - Een aansluiting met een kleine capaciteit kan onder voorwaarden worden beschouwd
          als grootverbruikaansluiting, bijvoorbeeld als het een aansluiting betreft
          op een gesloten distributiesysteem of een aansluiting zoals bedoeld in [artikel
          1, lid 2 of 3 van de Elektriciteitswet 1998](https://wetten.overheid.nl/jci1.3:c:BWBR0009755&amp;hoofdstuk=1&amp;paragraaf=1&amp;artikel=1&amp;z=2022-10-01&amp;g=2022-10-01).
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        see_also:
        - https://wetten.overheid.nl/jci1.3:c:BWBR0037934&amp;hoofdstuk=2&amp;paragraaf=2.1&amp;artikel=2.1.3&amp;z=2022-05-18&amp;g=2022-05-18
        - https://wetten.overheid.nl/jci1.3:c:BWBR0037938&amp;hoofdstuk=1&amp;artikel=1.1&amp;z=2022-11-25&amp;g=2022-11-25
        range: Marktsegment
        required: true
      uitsluitend elektriciteitsproductie-eenheden:
        name: uitsluitend elektriciteitsproductie-eenheden
        description: indicatie of achter een aansluiting zich uitsluitend elektriciteitsproductie-eenheden
          bevinden en geen ander verbruik dan het eigen verbruik van de desbetreffende
          elektriciteitsproductie-eenheden
        comments:
        - Ook wel bekend als &#39;zuivere teruglevering&#39;.
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        see_also:
        - https://wetten.overheid.nl/jci1.3:c:BWBR0037951&amp;hoofdstuk=3&amp;paragraaf=3.7&amp;artikel=3.7.13.b&amp;z=2022-05-18&amp;g=2022-05-18
        range: Waar of onwaar
        required: true
      weekmax:
        name: weekmax
        description: indicatie of de kWmax per week gemeten moet worden
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        see_also:
        - https://wetten.overheid.nl/jci1.3:c:BWBR0037951&amp;hoofdstuk=3&amp;paragraaf=3.7&amp;artikel=3.7.5a&amp;z=2022-05-18&amp;g=2022-05-18
        range: Waar of onwaar
      deel van:
        name: deel van
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: &#39;*&#39;
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Netgebied
        required: false
        multivalued: false
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - EAN-code
  Allocatiepunt:
    name: Allocatiepunt
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    description: punt waar invoeding, onttrekking of verbruik van elektriciteit of
      gas wordt toegerekend aan een marktdeelnemer
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    source: https://wetten.overheid.nl/jci1.3:c:BWBR0037938&amp;z=2025-04-26&amp;g=2025-04-26
    slots:
    - EAN-code
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - EAN-code
  Allocatiepunt bij aansluiting:
    name: Allocatiepunt bij aansluiting
    description: allocatiepunt toegekend aan een aansluiting
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    is_a: Allocatiepunt
    attributes:
      bij:
        name: bij
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: 1..*
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Aansluiting
        required: true
        multivalued: false
  Allocatiepunt bij netgebied:
    name: Allocatiepunt bij netgebied
    description: allocatiepunt toegekend aan een netgebied
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    is_a: Allocatiepunt
    attributes:
      bij:
        name: bij
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: 1..*
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Netgebied
        required: true
        multivalued: false
  Netgebied:
    name: Netgebied
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    description: aaneengesloten en samenhangend deel van een energienet van één netbeheerder,
      waarbinnen de processen allocatie en reconciliatie plaatsvinden
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    source: https://wetten.overheid.nl/jci1.3:c:BWBR0037938&amp;z=2025-04-26&amp;g=2025-04-26
    slots:
    - EAN-code
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - EAN-code
  Overdrachtspunt:
    name: Overdrachtspunt
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    exact_mappings:
    - nbnl:overdrachtspunt
    slots:
    - EAN-code
    attributes:
      deel van:
        name: deel van
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: 1..*
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Any
        required: true
        multivalued: false
        exactly_one_of:
        - range: Aansluiting
        - range: Netkoppeling
      in:
        name: in
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: 1..*
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Aansluitlocatie
        required: true
        multivalued: false
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - EAN-code
  Aansluitlocatie:
    name: Aansluitlocatie
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    description: plek waar zich het overdrachtspunt van een aansluiting of netkoppeling
      bevindt
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    attributes:
      locatienummer:
        name: locatienummer
        description: identificatie van een aansluitlocatie
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        required: true
      toegangsinstructie:
        name: toegangsinstructie
        description: beschrijving van wat je moet doen om een locatie binnen te kunnen
          of mogen gaan
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
      verdieping toegang:
        name: verdieping toegang
        description: aanduiding op welke verdieping de toegangsdeur van de aansluitlocatie
          zich bevindt
        comments:
        - Dit gegeven helpt bij het snel lokaliseren van storingen in hoogbouw.
        - De begande grond geldt als `0`. Als de toegang meer dan 1,5 m onder het
          maaiveld ligt, wordt als verdieping `-1` aangemerkt.
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        source: https://www.amsterdam.nl/stelselpedia/bag-index/catalogus-bag/objectklasse-vbo/kenmerk-bouwlaag/
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - locatienummer
  Locatieaanduiding:
    name: Locatieaanduiding
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    attributes:
      locatieomschrijving:
        name: locatieomschrijving
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
      van:
        name: van
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: 0..1
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Aansluitlocatie
        required: true
        multivalued: false
      afgeleid van:
        name: afgeleid van
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: &#39;*&#39;
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        range: Nummeraanduiding
        required: false
        multivalued: false
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - van
  Netkoppeling:
    name: Netkoppeling
    annotations:
      nbility_object:
        tag: nbility_object
        value: Aansluiting
      tijdlijn_geldigheid:
        tag: tijdlijn_geldigheid
        value: true
      tijdlijn_registratie:
        tag: tijdlijn_registratie
        value: true
    description: recht op het gebruik van één of meer verbindingen tussen twee energienetten
      of tussen een energienet en een interconnector
    comments:
    - Een koppeling met een gesloten distributiesysteem wordt in dit register beschouwd
      als netkoppeling als de beheerder gebruik maakt van het elektronische berichtenverkeer
      ten behoeve van het faciliteren van derdentoegang ([artikel 2.4, vierde lid
      van de Netcode elektriciteit](https://wetten.overheid.nl/jci1.3:c:BWBR0037940&amp;hoofdstuk=2&amp;paragraaf=2.1&amp;artikel=2.4&amp;z=2023-04-01&amp;g=2023-04-01)).
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
    source: https://wetten.overheid.nl/jci1.3:c:BWBR0037923&amp;hoofdstuk=1&amp;artikel=1.1&amp;z=2021-06-01&amp;g=2021-06-01
    slots:
    - EAN-code
    attributes:
      deel van:
        name: deel van
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: &#39;*&#39;
        comments:
        - De beheerder van het netgebied waartoe de netkoppeling behoort, is daarmee
          de beheerder van de netkoppeling.
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        required: true
        multivalued: false
      koppeling met:
        name: koppeling met
        annotations:
          inverse_cardinality:
            tag: inverse_cardinality
            value: &#39;*&#39;
        comments:
        - Deze relatie is optioneel voor het geval het te koppelen netgebied nog niet
          bekend is of als er geen sprake is van een gekoppeld netgebied, zoals bij
          een koppeling met een interconnector.
        from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
        required: false
        multivalued: false
    unique_keys:
      identificatie:
        unique_key_name: identificatie
        unique_key_slots:
        - EAN-code
  Nummeraanduiding:
    name: Nummeraanduiding
    annotations:
      external_registry:
        tag: external_registry
        value: &#39;[Basisregistratie Adressen en Gebouwen](https://data.overheid.nl/dataset/4aca03b9-0bb1-454f-9d5a-53bb910029d0)&#39;
    from_schema: https://netbeheernederland.nl/conceptueelinformatiemodel/aansluitingenregister
source_file: modellen/registers/aansluitingenregister/1.1.2/model.yaml

....

====

== Entiteiten




=== Aangeslotene



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Klant]

_nbnl:aangeslotene_

Zie ook https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.9&sub-paragraaf=2.9.2&artikel=2.9.2.1&z=2022-12-20&g=2022-12-20[Informatiecode elektriciteit en gas], https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=3&paragraaf=3.3&sub-paragraaf=3.3.1&artikel=3.3.1.1&z=2023-06-28&g=2023-06-28[Informatiecode elektriciteit en gas]

Aangeslotenen worden niet uniek geïdentificeerd. Daarom gaat het hier om een gegevensgroep bij een aansluiting, niet om een zelfstandige entiteit.

Tijdslijnen: geldigheid, registratie, effectuering, levensduur (moment van geboorte, moment van overlijden)




    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| geboortedatum 
a| 
Tekst +
_0..1_
| _datum van de bevalling waarbij de aangeslotene is geboren_
| naam 
a| 
Tekst +
_1_
| _naam van een organisatie of de achternaam (zonder tussenvoegsel) van een natuurlijk persoon_
| tussenvoegsel 
a| 
Tekst +
_0..1_
| _verzameling van een of meer voorzetsels en/of lidwoorden die aan de achternaam van een aangeslotene vooraf gaat en daarmee gezamenlijk de volledige achternaam vormt_
| voorletters 
a| 
Tekst +
_0..1_
| _verzameling letters die wordt gevormd door de eerste letter van alle in volgorde voorkomende voornamen van een aangeslotene_
| KVK-nummer 
a| 
Tekst +
_0..1_
| _identificatie van de maatschappelijke activiteit van de aangeslotene in het Handelsregister_

|===




==== Relaties

[cols="2,3",width="100%"]
|===
| Aangeslotene is ... | Omschrijving

a| link:#[^⚿^,title="Maakt deel uit van de identificatie"]beschikker over 
Aansluiting +
_0..1 → 1_
| 

|===






=== Aansluiting



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

_nbnl:aansluiting_

Een koppeling met een gesloten distributiesysteem wordt in dit register beschouwd als aansluiting als de beheerder geen gebruik maakt van het elektronische berichtenverkeer ten behoeve van het faciliteren van derdentoegang ([artikel 2.4, vierde lid van de Netcode elektriciteit](https://wetten.overheid.nl/jci1.3:c:BWBR0037940&hoofdstuk=2&paragraaf=2.1&artikel=2.4&z=2023-04-01&g=2023-04-01)).

Tijdslijnen: geldigheid, registratie




    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    

    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| link:#[^⚿^,title="Maakt deel uit van de identificatie"]EAN-code 
a| 
EAN-18 +
_1_
| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_
| energiedrager 
a| 
Energiedrager +
_0..1_
| _nbnl:energiedrager_
| gecontracteerde transportcapaciteit 
a| 
Tekst +
_0..1_
| _nbnl:gecontracteerde-transportcapaciteit_
| grootte 
a| 
Groot of klein +
_1_
| _aanduiding van het formaat van de aansluiting op basis van de gewenste aansluitcapaciteiten van de overdrachtspunten_

Validatie: als de gewenste aansluitcapaciteit van een van de overdrachtspunten 'groot' is of een geheel getal dan 'groot' anders 'klein'.
| marktsegment 
a| 
Marktsegment +
_1_
| _aanduiding van de categorie waartoe de aansluiting behoort, te weten kleinverbruikaansluiting of grootverbruikaansluiting_

Zie ook https://wetten.overheid.nl/jci1.3:c:BWBR0037934&hoofdstuk=2&paragraaf=2.1&artikel=2.1.3&z=2022-05-18&g=2022-05-18[Informatiecode elektriciteit en gas], https://wetten.overheid.nl/jci1.3:c:BWBR0037938&hoofdstuk=1&artikel=1.1&z=2022-11-25&g=2022-11-25[Begrippencode elektriciteit]

Een aansluiting met een kleine capaciteit kan onder voorwaarden worden beschouwd als grootverbruikaansluiting, bijvoorbeeld als het een aansluiting betreft op een gesloten distributiesysteem of een aansluiting zoals bedoeld in [artikel 1, lid 2 of 3 van de Elektriciteitswet 1998](https://wetten.overheid.nl/jci1.3:c:BWBR0009755&hoofdstuk=1&paragraaf=1&artikel=1&z=2022-10-01&g=2022-10-01).
| uitsluitend elektriciteitsproductie-eenheden 
a| 
Waar of onwaar +
_1_
| _indicatie of achter een aansluiting zich uitsluitend elektriciteitsproductie-eenheden bevinden en geen ander verbruik dan het eigen verbruik van de desbetreffende elektriciteitsproductie-eenheden_

Zie ook https://wetten.overheid.nl/jci1.3:c:BWBR0037951&hoofdstuk=3&paragraaf=3.7&artikel=3.7.13.b&z=2022-05-18&g=2022-05-18[Tarievencode elektriciteit]

Ook wel bekend als 'zuivere teruglevering'.
| weekmax 
a| 
Waar of onwaar +
_0..1_
| _indicatie of de kWmax per week gemeten moet worden_

Zie ook https://wetten.overheid.nl/jci1.3:c:BWBR0037951&hoofdstuk=3&paragraaf=3.7&artikel=3.7.5a&z=2022-05-18&g=2022-05-18[Tarievencode elektriciteit]

|===




==== Relaties

[cols="2,3",width="100%"]
|===
| Aansluiting is ... | Omschrijving

a| deel van 
Netgebied +
_* → 0..1_
| 

|===






=== Aansluitlocatie



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

_plek waar zich het overdrachtspunt van een aansluiting of netkoppeling bevindt_

Tijdslijnen: geldigheid, registratie




    
    
    
        
    

    
    
    
        
    

    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| link:#[^⚿^,title="Maakt deel uit van de identificatie"]locatienummer 
a| 
Tekst +
_1_
| _identificatie van een aansluitlocatie_
| toegangsinstructie 
a| 
Tekst +
_0..1_
| _beschrijving van wat je moet doen om een locatie binnen te kunnen of mogen gaan_
| verdieping toegang 
a| 
Tekst +
_0..1_
| _aanduiding op welke verdieping de toegangsdeur van de aansluitlocatie zich bevindt_

Bron: https://www.amsterdam.nl/stelselpedia/bag-index/catalogus-bag/objectklasse-vbo/kenmerk-bouwlaag/[None]

Dit gegeven helpt bij het snel lokaliseren van storingen in hoogbouw.

De begande grond geldt als `0`. Als de toegang meer dan 1,5 m onder het maaiveld ligt, wordt als verdieping `-1` aangemerkt.

|===









=== Allocatiepunt



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

_punt waar invoeding, onttrekking of verbruik van elektriciteit of gas wordt toegerekend aan een marktdeelnemer_

Bron: https://wetten.overheid.nl/jci1.3:c:BWBR0037938&z=2025-04-26&g=2025-04-26[Begrippencode elektriciteit]

Tijdslijnen: geldigheid, registratie




    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| link:#[^⚿^,title="Maakt deel uit van de identificatie"]EAN-code 
a| 
EAN-18 +
_1_
| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

|===









=== Allocatiepunt bij aansluiting


Specialisatie van 
Allocatiepunt


_allocatiepunt toegekend aan een aansluiting_




    
    
    
        
    





==== Relaties

[cols="2,3",width="100%"]
|===
| Allocatiepunt bij aansluiting is ... | Omschrijving

a| bij 
Aansluiting +
_1..* → 1_
| 

|===






=== Allocatiepunt bij netgebied


Specialisatie van 
Allocatiepunt


_allocatiepunt toegekend aan een netgebied_




    
    
    
        
    





==== Relaties

[cols="2,3",width="100%"]
|===
| Allocatiepunt bij netgebied is ... | Omschrijving

a| bij 
Netgebied +
_1..* → 1_
| 

|===






=== Locatieaanduiding



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

Tijdslijnen: geldigheid, registratie




    
    
    
        
    

    
    
    
        
    

    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| locatieomschrijving 
a| 
Tekst +
_0..1_
| 

|===




==== Relaties

[cols="2,3",width="100%"]
|===
| Locatieaanduiding is ... | Omschrijving

a| link:#[^⚿^,title="Maakt deel uit van de identificatie"]van 
Aansluitlocatie +
_0..1 → 1_
| 
a| afgeleid van Nummeraanduiding ([Basisregistratie Adressen en Gebouwen](https://data.overheid.nl/dataset/4aca03b9-0bb1-454f-9d5a-53bb910029d0)) +
_* → 0..1_
| 

|===






=== Netgebied



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

_aaneengesloten en samenhangend deel van een energienet van één netbeheerder, waarbinnen de processen allocatie en reconciliatie plaatsvinden_

Bron: https://wetten.overheid.nl/jci1.3:c:BWBR0037938&z=2025-04-26&g=2025-04-26[Begrippencode elektriciteit]

Tijdslijnen: geldigheid, registratie




    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| link:#[^⚿^,title="Maakt deel uit van de identificatie"]EAN-code 
a| 
EAN-18 +
_1_
| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

|===









=== Netkoppeling



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

_recht op het gebruik van één of meer verbindingen tussen twee energienetten of tussen een energienet en een interconnector_

Bron: https://wetten.overheid.nl/jci1.3:c:BWBR0037923&hoofdstuk=1&artikel=1.1&z=2021-06-01&g=2021-06-01[Begrippencode gas]

Een koppeling met een gesloten distributiesysteem wordt in dit register beschouwd als netkoppeling als de beheerder gebruik maakt van het elektronische berichtenverkeer ten behoeve van het faciliteren van derdentoegang ([artikel 2.4, vierde lid van de Netcode elektriciteit](https://wetten.overheid.nl/jci1.3:c:BWBR0037940&hoofdstuk=2&paragraaf=2.1&artikel=2.4&z=2023-04-01&g=2023-04-01)).

Tijdslijnen: geldigheid, registratie




    
    
    
        
    

    
    
    
        
    

    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| link:#[^⚿^,title="Maakt deel uit van de identificatie"]EAN-code 
a| 
EAN-18 +
_1_
| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_
| deel van 
a| 
Tekst +
_1_
| De beheerder van het netgebied waartoe de netkoppeling behoort, is daarmee de beheerder van de netkoppeling.
| koppeling met 
a| 
Tekst +
_0..1_
| Deze relatie is optioneel voor het geval het te koppelen netgebied nog niet bekend is of als er geen sprake is van een gekoppeld netgebied, zoals bij een koppeling met een interconnector.

|===











=== Overdrachtspunt



NBility-object: https://nbility-model.github.io/NBility-business-capabilities-Archi/?view=id-8becf2d90261476faa9d53240e6cf2c8)[Aansluiting]

_nbnl:overdrachtspunt_

Tijdslijnen: geldigheid, registratie




    
    
    
        
    

    
    
    
        
    

    
    
    
        
    



==== Eigenschappen

[cols="2,1,5",width="100%"]
|===
| Eigenschap | Waardesoort | Omschrijving

| link:#[^⚿^,title="Maakt deel uit van de identificatie"]EAN-code 
a| 
EAN-18 +
_1_
| _unieke cijfercombinatie volgens de Europese Artikelnummer-standaard_

|===




==== Relaties

[cols="2,3",width="100%"]
|===
| Overdrachtspunt is ... | Omschrijving

a| deel van óf 
Aansluiting{nbsp}óf 
Netkoppeling +
_1..* → 1_
| 
a| in 
Aansluitlocatie +
_1..* → 1_
| 

|===





== Waardesoorten en waardelijsten


=== Waardesoorten

[cols="1,4,1,1",width="100%"]
|===
| Waardesoort | Omschrijving | Gebaseerd op | Patroon

| <<id_safe(name),EAN-18>>
| _Europees artikelnummer van achttien cijfers_
| 
Tekst
| `^[0-9]{18}$`
| <<id_safe(name),Datum>>
| _kalenderdatum, zonder tijdsaanduiding_
| date
| 
| <<id_safe(name),Geheel getal>>
| _getal zonder decimalen_
| int
| 
| <<id_safe(name),Getal>>
| _voorstelling van een hoeveelheid_
| float
| 
| <<id_safe(name),Tekst>>
| _aanduiding bedoeld voor mensen, zonder vaste structuur of betekenis_
| str
| 
| <<id_safe(name),Tijdsduur>>
| _lengte van een tijdsinterval, bijvoorbeeld een uur of een dag_
| duration
| 
| <<id_safe(name),Tijdstip>>
| _exacte aanduiding van datum en tijd, inclusief eventueel tijdzone-informatie_
| datetime
| 
| <<id_safe(name),Waar of onwaar>>
| _binaire aanduiding die aangeeft of een propositie of kenmerk van toepassing is (waar) of niet van toepassing is (onwaar)_
| bool
| 
| <<id_safe(name),URI>>
| _uniforme aanduiding van een externe of interne bron_
| uri
| 


|===




=== Waardelijsten


==== <<id_safe(name),Energiedrager>>



[cols="1,2",width="100%"]
|===
| Waarde | Omschrijving

| <<id_safe(name),elektriciteit>>
| 
| <<id_safe(name),gas>>
| 
| <<id_safe(name),waterstof>>
| 
|===


==== <<id_safe(name),Groot of klein>>



[cols="1,2",width="100%"]
|===
| Waarde | Omschrijving

| <<id_safe(name),groot>>
| 
| <<id_safe(name),klein>>
| 
|===


==== <<id_safe(name),Marktsegment>>



[cols="1,2",width="100%"]
|===
| Waarde | Omschrijving

| <<id_safe(name),grootverbruikaansluiting>>
| 
| <<id_safe(name),kleinverbruikaansluiting>>
| 
|===


