title: NBNL Conceptuele Informatiemodellen
theme: just-the-docs

# Zet root van content op / voor correcte linkopbouw
baseurl: ""

# Toon de juiste navigatie
just_the_docs:
  collections:
    pages:
      output: true
      permalink: /:path/
  logo: ""
  search_enabled: true
  show_last_modified_time: false

# Neem je statische bestanden op (zoals SVG's)
include:
  - "**/*.svg"
