name: Create and publish docs

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install LinkML
        run: pip install linkml pyyaml

      - name: Create docs per model version
        run: |
          mkdir -p docs

          for model in modellen/*; do
            modelname=$(basename "$model")
            for version in "$model"/*; do
              versionid=$(basename "$version")
              echo "📄 Process $modelname version $versionid"
              gen-doc \
                --template-directory templates \
                -d docs/$modelname/$versionid \
                "$version/model.yaml"
            done
          done

      - name: Create central index.md
        run: python scripts/generate_index.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
